### ISSUE TITLE
"You need a better connection to play"

### ISSUE THREAD

**Issue by jole-srebrnaruka** [ChristopherKlay/StadiaEnhanced#45] opened 2020-12-21 08:26 UTC
Hi there, thanks for all of your hard work!

I am able to get into games and get them working, but after about 3 mins I get booted with the "You need a better connection to play". Is it possible for the extension to prevent this message from booting me and allow me to continue playing?

![image](https://user-images.githubusercontent.com/76426130/102755064-fc905a80-43c1-11eb-913c-96b919d14afa.png)

I'm trying to play with a VPN from Australia, so I understand that there is little that can be done to decrease my ping (from what I understand the minimum is guaranteed to be 170ms because of the distance). The thing is that i actually don't mind the quality and would keep playing if I could!

**Comment by ChristopherKlay** [comment] 2020-12-21 12:39
Hiding the UI elements and/or warning wouldn't be an issue, but i don't think there is a way to stop Stadia from closing the stream.

There's a check in place that simply terminates the connection, if the connection check runs into issues - which can be based off dropped frames/packages, but also ping.

**Comment by jole-srebrnaruka** [comment] 2020-12-21 12:42
Could the stats being sent back be intercepted and modified to be a bit
lower perhaps?

**Comment by ChristopherKlay** [comment] 2020-12-21 12:55
The issue is, even if i find a way to modify them, they would still take too long to actually be received, which would still trigger the connection cut.

To explain it really simple; Even if i could fake the "travel data", the package would still be received late and the "person" receiving it would notice.

**Comment by jole-srebrnaruka** [comment] 2020-12-21 12:57
Ah, I see. Thanks for the explanation!

Fingers crossed for an Australian Stadia release soon! 🤞

**Comment by jole-srebrnaruka** [comment] 2020-12-21 13:10
Actually I've noticed that I don't get booted on the android Stadia app,
even with exactly the same network conditions. Could that help?

**Comment by ChristopherKlay** [comment] 2020-12-21 13:17
That's mostly because the android app can afaik stream at even lower resolutions.

The desktop version is sadly restricted to 720p/1080p/1440p/2160p.

**Closed** 2020-12-27 13:23 UTC
