### ISSUE TITLE
Library Doesn't Scroll With Controller With Scrollbars Enabled

### ISSUE THREAD

**Issue by djohannes** [ChristopherKlay/StadiaEnhanced#68] opened 2021-01-03 22:14 UTC
If you enable that the scrollbars are always visible, you can't scroll through your library with a controller (at least with the Stadia controller, I don't have another controller to try). It just stops at the last game visible.

**Comment by ChristopherKlay** [comment] 2021-01-03 22:44
Noted, but i can't promise a quick fix for this.

The issue is that Stadias implementation of the controller, doesn't allow scrolling of a div; which is most likely why scrollbars are disabled by default. Just enabling the scrollbar (`overflow-y: scroll`) sadly doesn't actually show the scrollbars, they only show up when i also set the height of the element to 100%; which is what enables scrollbars, but also breaks controller scrolling due said issue above.

**Comment by djohannes** [comment] 2021-01-03 22:46
@ChristopherKlay Ah thank you for the explanation! Is it possible to "detect" if I use a controller or not and change the setting accordingly? I wouldn't mind not seeing the scrollbars if I have a controller connected, but it would be nice if I wouldn't need to turn on/off this feature by myself.

**Comment by ChristopherKlay** [comment] 2021-01-03 22:49
Detecting the current control method and enabling/disabling the feature based on that should certainly be possible.
I just have to figure out at which point Stadia actually "switches", especially when using the wifi connected input.

I'll update this when i find a solution (:

**Comment by ChristopherKlay** [comment] 2021-01-16 18:02
Google solved this on their end and also included scrollbars on their own.
`1.8.7` removes the feature from Enhanced and everything will work (:

**Comment by djohannes** [comment] 2021-01-16 19:45
Just saw it! Thank god this is native now :)

**Closed** 2021-01-17 06:23 UTC
Labels: bug
